---
title: "Zillow Project Report"
author: "Liz Vincent"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,message = F, warning = F,fig.align = "center")

packages<-c("data.table","corrplot","dplyr","ggplot2","magrittr","stringi","stringr","rebus","gridExtra","reshape2","ggmap","tidyr","caret","xgboost","Matrix","ranger","grid","cowplot","lubridate")

for (i in packages){
  if(!require(i,character.only = T,quietly=T,warn.conflicts = F)){
    install.packages(i)
  }
  require(i,character.only = T,quietly=T,warn.conflicts = F)
}

properties_2016<-read.csv("properties_2016.csv",stringsAsFactors = F)  # This takes a while...~3 million rows, 58 columns
train_2016<-read.csv("train_2016_v2.csv")

label<-c("Framing Type","Perimeter Living Area Sqft.","Basement Sqft.","Type of Floors in Multi-Story House","Yard Building Sqft.","Fireplace, Y/N","Architecture Style","Construction Material","Unfinished and Finished Sqft.","Type of Deck","Pool Sqft.","Spa or Hot Tub, Y/N","Pool with Spa or Hot Tub, Y/N","Tax Delinquency, Y/N","Year of Tax Delinquency","Spa or Hot Tub, Y/N","Patio Sqft.","Total Sqft.","First Floor Living Area Sqft.","First Floor Living Area Sqft.","No. Fireplaces","No. 3/4 Baths","Pool without Spa or Hot Tub, Y/N","No. Pools","No. Stories","Type of Air Conditioning","No. Garages","Garage Sqft.","Neighborhood ID","Type of Heating System","Building Condition","No. Units","Lot Sqft.","Total Finished Living Area Sqft.","City ID","Total No. Baths","No. Full Baths","Year Built","Total Finished Living Area Sqft.","Census Tract and Block ID","Assessed Value of Structure","Zip Code","Total Property Tax","Total Tax Assessed Value of Parcel","Assessed Value of Land","Parcel ID","Log Error","Transaction Date","Total No. Baths","No. Bedrooms","FIPS Code","Longitude","Latitude","Zoning at County Level","Zoning","Description of Zoning","Census Tract and Block ID","County ID","Total No. Rooms","Asessment Year")

category<-c("buildingclasstypeid","finishedsquarefeet13","basementsqft","storytypeid","yardbuildingsqft26","fireplaceflag","architecturalstyletypeid","typeconstructiontypeid","finishedsquarefeet6","decktypeid","poolsizesum","pooltypeid10","pooltypeid2","taxdelinquencyflag","taxdelinquencyyear","hashottuborspa","yardbuildingsqft17","finishedsquarefeet15","finishedfloor1squarefeet","finishedsquarefeet50","fireplacecnt","threequarterbathnbr","pooltypeid7","poolcnt","numberofstories","airconditioningtypeid","garagecarcnt","garagetotalsqft","regionidneighborhood","heatingorsystemtypeid","buildingqualitytypeid","unitcnt","lotsizesquarefeet","finishedsquarefeet12","regionidcity","calculatedbathnbr","fullbathcnt","yearbuilt","calculatedfinishedsquarefeet","censustractandblock","structuretaxvaluedollarcnt","regionidzip","taxamount","taxvaluedollarcnt","landtaxvaluedollarcnt","parcelid","logerror","transactiondate","bathroomcnt","bedroomcnt","fips","latitude","longitude","propertycountylandusecode","propertylandusetypeid","propertyzoningdesc","rawcensustractandblock","regionidcounty","roomcnt","assessmentyear")

var_key<-data.frame(category, label)
```

```{r train_variable_class}
train_2016<-merge(train_2016,properties,by="parcelid")
factor_vars <- str_subset(names(train_2016),pattern="id")
factor_vars <- c(factor_vars,"fips","propertycountylandusecode","propertyzoningdesc","rawcensustractandblock","censustractandblock")
train_2016[,factor_vars]<-lapply(train_2016[,factor_vars],factor)
```

```{r train_missingness, echo=F}
# Count the number of NAs or empty strings in each column of properties_2016
missingness_2016_preimputation<-lapply(train_2016,function(x){
    ifelse(is.character(x),
          sum(str_detect(x,pattern=START %R% END)),
          sum(is.na(x))
  )
})

# Format missingness
missingness_2016_preimputation<-round(unlist(missingness_2016_preimputation)/nrow(train_2016)*100,3)
missingness_2016_preimputation<-sort(missingness_2016_preimputation,decreasing=T)
missingness_2016_preimputation<-as.data.frame(missingness_2016_preimputation)
missingness_2016_preimputation$var<-row.names(missingness_2016_preimputation)
row.names(missingness_2016_preimputation)<-seq(1:nrow(missingness_2016_preimputation))
missingness_2016_preimputation<-select(missingness_2016_preimputation,c("var","missingness_2016_preimputation"))
missingness_2016_preimputation<-missingness_2016_preimputation %>% mutate(category = lapply(missingness_2016_preimputation,function(x){if(x < 5){"<5%"} else if(x>=5 & x <= 95){">=5%, <=95%"} else{">95%"}}))
missingness_2016_preimputation$category<-as.character(missingness_2016_preimputation$category)

p1 <- 
  ggplot(missingness_2016_preimputation,aes(x=reorder(var, missingness_2016_preimputation),y=missingness_2016_preimputation,fill=category)) +
  geom_col() +
  scale_fill_manual(breaks=c(">95%",">=5%, <=95%","<5%"),values=c("#377eb8","black","#e41a1c")) +
  scale_y_continuous(limits = c(NA,100),expand = c(0,0)) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),panel.grid.major.y = element_blank(),legend.position = c(0.875,0.09), axis.ticks=element_blank()) +
  guides(fill=guide_legend(title = "Missingness")) +
  labs(y="Missingness (%)",x=element_blank()) +
  scale_x_discrete(breaks=as.character(var_key$category), labels=as.character(var_key$label)) +
  coord_flip()
```

```{r}
character_variables<-names(which(sapply(train_2016, class) == "character")) # Get names of all columns whose entries are characters

tmp1<-as.data.frame(is.na(train_2016[,!(names(train_2016) %in% character_variables)])) # Check if NA for all columns whose entries are not characters
tmp2<-as.data.frame(lapply(train_2016[,names(train_2016) %in% character_variables],function(x){ 
  str_detect(x,pattern = START %R% END)
}))  # Check if empty string for all columns whose entries are characters
df_missing<-cbind(tmp1,tmp2)
df_missing<-sapply(df_missing,as.numeric)

cor_logerror_missing<-cor(df_missing,train_2016$logerror)
cor_logerror_missing<-cor_logerror_missing[!is.na(cor_logerror_missing),]
cor_logerror_missing<-as.data.frame(cor_logerror_missing)
cor_logerror_missing$type<-row.names(cor_logerror_missing)

p2<-
  ggplot(cor_logerror_missing,aes(x=reorder(type, abs(cor_logerror_missing)), y=abs(cor_logerror_missing),fill=ifelse(cor_logerror_missing < 0, "Negative","Positive"))) +
  geom_col() +
  scale_fill_brewer(palette = "Set1") +
  scale_y_continuous(limits = c(NA,0.024),expand = c(0,0), breaks=c(0,0.006,0.012,0.018,0.024)) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),panel.grid.major.y = element_blank(),legend.position = c(0.875,0.09), axis.ticks=element_blank(),plot.margin = unit(c(0.01,0.03,0.01,0), "null")) +
  coord_flip() +
  guides(fill=guide_legend("Direction of\nCorrelation")) +
  scale_x_discrete(breaks=as.character(var_key$category), labels=as.character(var_key$label)) +
  labs(y= "Absolute Value of Correlation", x="")

pg<-plot_grid(p1, p2, ncol=2, labels=c("A", "B"))
save_plot("missingness.pdf", pg, base_height=8, base_width = 16)
```

```{r, fig.height=6, fig.width=8}
coordinates<-properties_2016[,c("longitude","latitude")]

coordinates$latitude<-as.numeric(str_replace(coordinates$latitude, pattern=capture(dgt(2)) %R% capture(one_or_more(DGT)),replacement=REF1 %R% DOT %R% REF2))
coordinates$longitude<-as.numeric(str_replace(coordinates$longitude, pattern=capture("-" %R% dgt(3)) %R% capture(one_or_more(DGT)),replacement=REF1 %R% DOT %R% REF2))

get_density <- function(x, y, n = 100) {
  dens <- MASS::kde2d(x = x, y = y, n = n)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
#cali <- c(left = -125, bottom = 30, right = -115, top = 40)
map <- get_googlemap(center=c(lon = -118.4, lat=34), zoom = 8, maptype = "roadmap")
p<-ggmap(map) +
  geom_point(aes(x = longitude, y = latitude,color=get_density(x=longitude,y=latitude)), data = na.omit(coordinates)) +
  scale_color_gradientn("Density",colors = c("blue4","blue","springgreen2","yellow","orange","red","red3"), breaks=c(0.1,3),labels=c("low","high")) +
  theme(axis.text = element_blank(),axis.ticks = element_blank(),axis.title = element_blank(),legend.position = c(0.08,0.12),legend.background = element_blank(), axis.line = element_blank())
```